#!/usr/bin/env bash
#
# Magento Continuous Integration Tools
#
# NOTICE OF LICENSE
#
# This source file is subject to the Open Software License (OSL 3.0)
# that is bundled with this package in the file LICENSE.txt.
# It is also available through the world-wide-web at this URL:
# http://opensource.org/licenses/osl-3.0.php
#
# @category   EcomDev
# @package    EcomDev/MageCI
# @copyright  Copyright (c) 2013 EcomDev BV (http://www.ecomdev.org)
# @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
# @author     Ivan Chepurnyi <ivan.chepurnyi@ecomdev.org>

current_dir=$(pwd)

# create bin directory in current dir
if [ ! -d "$current_dir/bin" ]
then
  mkdir -p $current_dir/bin
fi

wget -q -O $current_dir/bin/mage-ci https://raw.github.com/EcomDev/MageCI/master/bin/mage-ci --no-check-certificate
chmod +x $current_dir/bin/mage-ci